version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "dkg.js"
    assignees:
      - "marko03kostic"
    target-branch: "main"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
